import Enum from '../../../lib/base/enum/index.js';

export default new Enum([
    {value: 'Foreign Crimson', key: 'FOREIGN_CRIMSON', hex: 'C91F37'},
    {value: 'Red Orange', key: 'RED_ORANGE', hex: 'DC3023'},
    {value: 'Cochineal Red', key: 'COCHINEAL_RED', hex: '9D2933'},
    {value: 'Monza', key: 'MONZA', hex: 'CF000F'},
    {value: 'Brewed Mustard-brown', key: 'BREWED_MUSTARD_BROWN', hex: 'E68364'},
    {value: 'Pomegranate', key: 'POMEGRANATE', hex: 'F22613'},
    {value: 'Scarlet', key: 'SCARLET', hex: 'CF3A24'},
    {value: 'Pure Crimson', key: 'PURE_CRIMSON', hex: 'C3272B'},
    {value: 'True Red', key: 'TRUE_RED', hex: '8F1D21'},
    {value: 'Chestnut Rose', key: 'CHESTNUT_ROSE', hex: 'D24D57'},
    {value: 'One Kin Dye', key: 'ONE_KIN_DYE', hex: 'F08F907'},
    {value: 'Peach-colored', key: 'PEACH_COLORED', hex: 'F47983'},
    {value: 'Red Plum Colored', key: 'RED_PLUM_COLORED', hex: 'DB5A6B'},
    {value: 'Medium Crimson', key: 'MEDIUM_CRIMSON', hex: 'C93756'},
    {value: 'Cherry Blossom Color', key: 'CHERRY_BLOSSOM_COLOR', hex: 'FCC9B9'},
    {value: 'Washed-out Crimson', key: 'WASHED_OUT_CRIMSON', hex: 'FFB3A7'},
    {value: 'Radical Red', key: 'RADICAL_RED', hex: 'F62459'},
    {value: 'Ibis Wing Color', key: 'IBIS_WING_COLOR', hex: 'F58F84'},
    {value: 'Wisteria Purple', key: 'WISTERIA_PURPLE', hex: '875F9A'},
    {value: 'Bellflower Color', key: 'BELLFLOWER_COLOR', hex: '5D3F6A'},
    {value: 'Wisteria Color', key: 'WISTERIA_COLOR', hex: '89729E'},
    {value: 'Iris Color', key: 'IRIS_COLOR', hex: '763568'},
    {value: 'Tatarian Aster Color', key: 'TATARIAN_ASTER_COLOR', hex: '8D608C'},
    {value: 'Thin Color', key: 'THIN_COLOR', hex: 'A87CA0'},
    {value: 'Violet Color', key: 'VIOLET_COLOR', hex: '5B3256'},
    {value: 'Medium Purple', key: 'MEDIUM_PURPLE', hex: 'BF55EC'},
    {value: 'Studio', key: 'STUDIO', hex: '8E44AD'},
    {value: 'Wisteria', key: 'WISTERIA', hex: '9B59B6'},
    {value: 'Light Wisteria', key: 'LIGHT_WISTERIA', hex: 'BE90D4'},
    {value: 'Sky Color', key: 'SKY_COLOR', hex: '4D8FAC'},
    {value: 'Ultramarine Color', key: 'ULTRAMARINE_COLOR', hex: '5D8CAE'},
    {value: 'Picton Blue', key: 'PICTON_BLUE', hex: '22A7F0'},
    {value: 'Dodger Blue', key: 'DODGER_BLUE', hex: '19B5FE'},
    {value: 'Picton Blue', key: 'PICTON_BLUE', hex: '59ABE3'},
    {value: 'Light Blue Color', key: 'LIGHT_BLUE_COLOR', hex: '48929B'},
    {value: 'Thousand Herb', key: 'THOUSAND_HERB', hex: '317589'},
    {value: 'Jordy Blue', key: 'JORDY_BLUE', hex: '89C4F4'},
    {value: 'Steel Blue', key: 'STEEL_BLUE', hex: '4B77BE'},
    {value: 'Lapis Lazuli Color', key: 'LAPIS_LAZULI_COLOR', hex: '1F4788'},
    {value: 'Navy Blue Color', key: 'NAVY_BLUE_COLOR', hex: '003171'},
    {value: 'Hanada', key: 'HANADA', hex: '044F67'},
    {value: 'Indigo Color', key: 'INDIGO_COLOR', hex: '264348'},
    {value: 'Siskin Sprout Yellow', key: 'SISKIN_SPROUT_YELLOW', hex: '7A942E'},
    {value: 'Young Green Onion', key: 'YOUNG_GREEN_ONION', hex: '8DB255'},
    {value: 'Fresh Onion', key: 'FRESH_ONION', hex: '5B8930'},
    {value: 'Young Bamboo Color', key: 'YOUNG_BAMBOO_COLOR', hex: '6B9362'},
    {value: 'Patina', key: 'PATINA', hex: '407A52'},
    {value: 'Green Bamboo', key: 'GREEN_BAMBOO', hex: '006442'},
    {value: 'Gossip', key: 'GOSSIP', hex: '87D37C'},
    {value: 'Eucalyptus', key: 'EUCALYPTUS', hex: '26A65B'},
    {value: 'Jungle Green', key: 'JUNGLE_GREEN', hex: '26C281'},
    {value: 'Observatory', key: 'OBSERVATORY', hex: '049372'},
    {value: 'Jungle Green', key: 'JUNGLE_GREEN', hex: '2ABB9B'},
    {value: 'Mountain Meadow', key: 'MOUNTAIN_MEADOW', hex: '16A085'},
    {value: 'Turquoise', key: 'TURQUOISE', hex: '36D7B7'},
    {value: 'Free Speech Aquamarine', key: 'FREE_SPEECH_AQUAMARINE', hex: '03A678'},
    {value: 'Ocean Green', key: 'OCEAN_GREEN', hex: '4DAF7C'},
    {value: 'Patrinia Flowers', key: 'PATRINIA_FLOWERS', hex: 'D9B611'},
    {value: 'Amur Cork Tree', key: 'AMUR_CORK_TREE', hex: 'F3C13A'},
    {value: 'Ripe Lemon', key: 'RIPE_LEMON', hex: 'F7CA18'},
    {value: 'Japanese Triandra Grass', key: 'JAPANESE_TRIANDRA_GRASS', hex: 'E2B13C'},
    {value: 'Rapeseed Oil-colored', key: 'RAPESEED_OIL_COLORED', hex: 'A17917'},
    {value: 'Cream Can', key: 'CREAM_CAN', hex: 'F5D76E'},
    {value: 'Saffron', key: 'SAFFRON', hex: 'F4D03F'},
    {value: 'Bright Golden Yellow', key: 'BRIGHT_GOLDEN_YELLOW', hex: 'FFA400'},
    {value: 'Sumac-dyed', key: 'SUMAC_DYED', hex: 'E08A1E'},
    {value: 'Gamboge', key: 'GAMBOGE', hex: 'FFB61E'},
    {value: 'Corn-colored', key: 'CORN_COLORED', hex: 'FAA945'},
    {value: 'Egg-colored', key: 'EGG_COLORED', hex: 'FFA631'},
    {value: 'Floral Leaf-colored', key: 'FLORAL_LEAF_COLORED', hex: 'FFB94E'},
    {value: 'Golden Fallen Leaves', key: 'GOLDEN_FALLEN_LEAVES', hex: 'E29C45'},
    {value: 'Ecstasy', key: 'ECSTASY', hex: 'F9690E'},
    {value: 'Amber', key: 'AMBER', hex: 'CA6924'},
    {value: 'Lightning Yellow', key: 'LIGHTNING_YELLOW', hex: 'F5AB35'},
    {value: 'Silver', key: 'SILVER', hex: 'BFBFBF'},
    {value: 'Cararra', key: 'CARARRA', hex: 'F2F1EF'},
    {value: 'Silver Sand', key: 'SILVER_SAND', hex: 'BDC3C7'},
    {value: 'Porcelain', key: 'PORCELAIN', hex: 'ECF0F1'},
    {value: 'Pumice', key: 'PUMICE', hex: 'D2D7D3'},
    {value: 'Harbor Rat', key: 'HARBOR_RAT', hex: '757D75'},
    {value: 'Gallery', key: 'GALLERY', hex: 'EEEEEE'},
    {value: 'Edward', key: 'EDWARD', hex: 'ABB7B7'},
    {value: 'Lynch', key: 'LYNCH', hex: '6C7A89'},
    {value: 'Cascade', key: 'CASCADE', hex: '95A5A6'},
]);
